### ISSUE TITLE
Allow searching across all users

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/D4S2#107]
As of PR #105 the D4S2 v2 API will provide the ability to view a list of possible users to deliver a project to. This is backed by the DukeDS [v1/users](https://api.dataservice.duke.edu/apiexplorer#!/users/getApiV1Users) endpoint.
Unfortunately this isn't the list of all possible users. This is just those users that have used DukeDS.

There is a [v1/auth_providers/{id}/affiliates](https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/getApiV1AuthProvidersIdAffiliates) endpoint that returns a list of all possible users that could be registered with DukeDS. This endpoint requires the `full_name_contains` query parameter to be filled in with at least 3 characters.
The response is an array of users with a `uid` field that can be POSTed to the DukeDS [v1/auth_providers/{id}/affiliates/{uid}/dds_user](https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/postApiV1AuthProvidersIdAffiliatesUidDdsUser) endpoint to register the user with DukeDS.

DukeDSClient supports adding a new user via the [DataServiceApi .auth_provider_add_user](https://github.com/Duke-GCB/DukeDSClient/blob/434844a2d324a926d17630584efd19edc7a059a9/ddsc/core/ddsapi.py#L928-L938) method. There is no support for listing the affiliates in DukeDSClient.

**Comment by dleehr** [comment]
Discussed this issue with @johnbradley at length today on how to let senders find and select DukeDS Users as recipients from [datadelivery-ui](https://github.com/Duke-GCB/datadelivery-ui). We noted the following issues with the current implementation.

1. Only existing Duke DS Users can be selected as recipients. This is about 450 possible recipients. Registering Duke DS users can be done with an API call but we're not making that call from D4S2 yet.
2. Before selecting or filtering, we fetch the entire list of DukeDS Users, which takes about 20s right now. Background: https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/1103.
3. We'd expect core facilities to search by Name, Email, or NetID - as they would when drafting an email. Picking (or filtering) from a list of 450+ users is likely not how users would like to select a recipient.

So we propose the following changes:

1. In D4S2, implement an endpoint to search for Duke users by Name, email, or NetID. This endpoint may be backed by querying [DukeDS - GET auth\_providers/:id/affiliates](
https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/getApiV1AuthProvidersIdAffiliates) or simple LDAP. The goal is to resolve a user to a NetID.
2. In D4S2, implement an endpoint to retrieve a Duke DS User ID, given a NetID.
    1. For people that are already Duke DS Users, there is no direct mechanism to lookup from NetID
    2. For people that are not Duke DS Users, the [DukeDS - POST auth\_providers/:id/affiliates/:uid/dds\_user](
https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/postApiV1AuthProvidersIdAffiliatesUidDdsUser) endpoint can create (and return) a Duke DS User from a NetID. We implemented this in Python [DukeDSClient - DataServiceApi](
https://github.com/Duke-GCB/DukeDSClient/blob/434844a2d324a926d17630584efd19edc7a059a9/ddsc/core/ddsapi.py#L928-L938)
3. In datadelivery-ui, replace the current select-recipient functionality with the following:
    1. Search box with result listing - search for users and allow choosing a user from the result list (keyed by NetID)
    2. Function to resolve that NetID to a DukeDS User, suitable for setting as the delivery recipient.

**Comment by dleehr** [comment]
Created https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/1235 to request improvements to lookup
