### ISSUE TITLE
Add option to grant sender more permissions on delivery acceptance

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/D4S2#167]
Currently, senders only get `project_viewer` permission on deliveries. We should add an option so that permissions are granted like `file_downloader` to senders on non-copied projects. Came up in meeting with core facility today

**Comment by johnbradley** [comment]
D4S2 is unaware if a project is copied or not. DukeDSClient handles creating a copy and sends the id of the copied project to D4S2.

**Comment by dleehr** [comment]
Ah that's right. Either way, let's default to giving file downloader access back to the sender for all delivered projects. That'll probably eliminate the need to copy in the first place, which is something we won't be doing from datadelivery-ui

**Comment by dleehr** [comment]
Related: https://github.com/Duke-GCB/DukeDSClient/issues/180
