### ISSUE TITLE
communication about sender permissions

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/D4S2#174]
The sender of a project retains permissions but there is no communication to the recipient of that.
As of https://github.com/Duke-GCB/D4S2/pull/173 the sender retains file download permissions.

**Comment by dleehr** [comment]
Let's add a email type for completed dds deliveries that act as a receipt to the recipient, telling them what data they've accepted and what permissions apply to that data set.

**Comment by dleehr** [comment]
And in the case of S3, we have an email to notify the recipient when the permissions have been applied. We may be able to combine that here, and I think we should, otherwise recipients would be getting 2 emails for every accepted delivery (plus the original delivery notification)

**Comment by dleehr** [comment]
Having second thoughts on whether or not this belongs in the **Beta UI** milestone. It's certainly a good idea for beta clients, but wouldn't necessarily hinder cores in exploring the delivery interface
