### ISSUE TITLE
Project needs a better name

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/D4S2#52]
Some ideas based on mythology

- Hermes (Greek)

> Hermes is considered a god of transitions and boundaries. He is described as quick and cunning, moving freely between the worlds of the mortal and divine. He is also portrayed as an **emissary and messenger of the gods**

- Mercury (Roman)

> Mercury is a major Roman god, being one of the Dii Consentes within the ancient Roman pantheon. He is the patron god of financial gain, commerce, eloquence (and thus poetry), **messages/communication** (including divination), travelers, boundaries, luck, trickery and thieves; he is also the guide of souls to the underworld.

**Comment by dleehr** [comment]
Derivative names: Merc, Emissary, or Envoy

**Comment by dleehr** [comment]
john [3:21 PM]  Project name: D3livery
dleehr [3:22 PM]  Duke Data Delivery Service! DDDS
john [3:22 PM]  D3S
dleehr [3:22 PM]  Duke Data Service Distribution System
john [3:22 PM]  D(DS)² (edited)
dleehr [3:23 PM]  Deetwo (edited)
john [3:24 PM]  We need to make a second release. Then we can ask people if they are using r2 deetwo.
dleehr [3:26 PM]  Then again, C3PO is a protocol droid, fluent in 6 million forms of communication
so maybe that’s _the droid we’re looking for_
[3:27]  messaging/communication/etc

**Comment by hlapp** [comment]
Perhaps some combination: hermes-d3, or d3-hermes.

Or in honor of C3PO, dee4ess2 (D4S2).

```
Duke             Data
Data       -     Distribution
Service          System
```

**Comment by dleehr** [comment]
I like D4S2.
